### ISSUE TITLE
README 디자인 수정

### ISSUE THREAD

**Issue by devFallingstar** [NESOY/Back-end-Developer-Interview-Questions#6]
README 상단 디자인을 조금 더 이쁘게 수정하는 것은 어떨까요?
[이 레포](https://github.com/JaeYeopHan/Interview_Question_for_Beginner)참고하여 비슷한 느낌으로 디자인 해보면 좋을 것 같습니다.

**Comment by NESOY** [comment]
아 제안 감사합니다. ㅎㅎ 
많은 분들이 편하게 보기 위해서는 디자인 좀 바꿔야 할 거 같네요 ㅎㅎ
Repo 참고해서 주말에 진행해보도록 하겠습니다 :)
