### ISSUE TITLE
hierarchy refactoring

### ISSUE THREAD

**Issue by devFallingstar** [NESOY/Back-end-Developer-Interview-Questions#7]
전체적인 자료를 세분화하여 나누고, README에서는 하이퍼링크를 통하여 해당 자료가 존재하는 디렉토리로 이동할 수 있도록 수정하면 어떨까 합니다!

아래로 쭉쭉 내려서 보기가 힘드네요.

**Comment by NESOY** [comment]
이 부분도 [#6] 디자인과 같이 고민해서 해결하도록 하겠습니다 :)
감사합니다.
